Algoritmo "Exercício 3"
// Desenvolver um programa que apresente os quadrados dos números inteiros de
// 15 a 200
Var
// Seção de Declarações das variáveis 
 contador, contadorf: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Exibindo números quadrdos de 15 a 200")

contador <- 15
enquanto ( contador <= 200 ) faca
         escreval( contadorf )
         contador <- contador + 1
         contadorf <- contador * contador
fimenquanto

Fimalgoritmo